import { EventEmitter, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup } from '@angular/forms';
import { IAdditionalButtons } from '../pla-dynamic-form/form.interface';
import * as i0 from "@angular/core";
export declare class PlaFormInputArrayComponent implements OnInit {
    private readonly formBuilder;
    pageState: 'View' | 'Edit';
    form: FormGroup;
    formArrayName: string;
    createItemFn: () => FormGroup;
    formSections: any[];
    isSubmitted: boolean;
    isLoadingPackage: boolean;
    isAllowAddAnyPosition: boolean;
    isDisplayNumberOrder: boolean;
    additionalButtons: IAdditionalButtons[];
    useDefaultDeleteButton: boolean;
    itemAdded: EventEmitter<number>;
    isSmallScreen: boolean;
    constructor(formBuilder: FormBuilder);
    ngOnInit(): void;
    getNestedFormGroup(i: number, key: string): FormGroup;
    get items(): FormArray;
    addItem(index: number): void;
    removeItem(index: number): void;
    private defaultCreateItem;
    onSubmit(): void;
    getControls(): FormGroup[];
    static ɵfac: i0.ɵɵFactoryDeclaration<PlaFormInputArrayComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PlaFormInputArrayComponent, "pla-form-input-array", never, { "pageState": { "alias": "pageState"; "required": false; }; "form": { "alias": "form"; "required": false; }; "formArrayName": { "alias": "formArrayName"; "required": false; }; "createItemFn": { "alias": "createItemFn"; "required": true; }; "formSections": { "alias": "formSections"; "required": true; }; "isSubmitted": { "alias": "isSubmitted"; "required": false; }; "isLoadingPackage": { "alias": "isLoadingPackage"; "required": false; }; "isAllowAddAnyPosition": { "alias": "isAllowAddAnyPosition"; "required": false; }; "isDisplayNumberOrder": { "alias": "isDisplayNumberOrder"; "required": false; }; "additionalButtons": { "alias": "additionalButtons"; "required": false; }; "useDefaultDeleteButton": { "alias": "useDefaultDeleteButton"; "required": false; }; }, { "itemAdded": "itemAdded"; }, never, never, true, never>;
}
