export declare enum AUTH_ERROR_CODE {
    SSO_SESSION_INVALID = "SSO_SESSION_INVALID",
    SSO_SESSION_EXPIRED = "SSO_SESSION_EXPIRED",
    TOKEN_INVALID = "TOKEN_INVALID",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    AUDIENCE_MISSING = "AUDIENCE_MISSING",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
    APPLICATION_TIMEOUT = "APPLICATION_TIMEOUT",
    SSO_TOKEN_EXPIRED = "SSO_TOKEN_EXPIRED"
}
