import { EventEmitter, OnChanges, OnInit } from '@angular/core';
import { Table, TableFilterEvent, TableLazyLoadEvent } from 'primeng/table';
import { FilterMetadata, SortEvent } from 'primeng/api';
import { IAppliedFilters, IFilterColumn, IPaginatorProperties, ITableColumn, ITableConfig } from '../../models/table.interface';
import * as i0 from "@angular/core";
export declare class PlaTableComponent<T = unknown> implements OnInit, OnChanges {
    table: Table;
    tableLoading: boolean;
    tableData: T[];
    tableColumns: ITableColumn<T>[];
    tableConfig: ITableConfig;
    appliedFilters: IAppliedFilters;
    applicationStorageName: string;
    tableName: string;
    onChangeTableFiltersEmit: EventEmitter<any>;
    first: number;
    rows: number;
    skeletonTable: number[];
    ngOnInit(): void;
    ngOnChanges(): void;
    get paginatorConfig(): IPaginatorProperties;
    customSort(event: SortEvent): void;
    onChangeFilter(event: TableFilterEvent): void;
    private isDate;
    onGetFilterFromLocalStorage(): void;
    private normalizeDateFilters;
    private buildDefaultFilters;
    onChangeTableFilters(event: TableLazyLoadEvent): void;
    getSortOrder(sortOrder: number | undefined | null, sortField: string | undefined): 'ASC' | 'DESC';
    transformFilterValue(input: Record<string, FilterMetadata | undefined>): IFilterColumn[];
    formatDate: (dateInput: string | string[]) => string | string[];
    private getOperator;
    static ɵfac: i0.ɵɵFactoryDeclaration<PlaTableComponent<any>, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PlaTableComponent<any>, "pla-table", never, { "tableLoading": { "alias": "tableLoading"; "required": true; }; "tableData": { "alias": "tableData"; "required": true; }; "tableColumns": { "alias": "tableColumns"; "required": true; }; "tableConfig": { "alias": "tableConfig"; "required": true; }; "appliedFilters": { "alias": "appliedFilters"; "required": false; }; "applicationStorageName": { "alias": "applicationStorageName"; "required": true; }; "tableName": { "alias": "tableName"; "required": true; }; }, { "onChangeTableFiltersEmit": "onChangeTableFiltersEmit"; }, never, never, true, never>;
}
